<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaGestaoEscolar" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SistemaGestaoEscolar.mssql.somee.com;Initial Catalog=SistemaGestaoEscolar;User ID=ALCSG_SQLLogin_1;Encrypt=False;Trust Server Certificate=True" SettingsObjectName="SGE.Data.Properties.Settings" SettingsPropertyName="SistemaGestaoEscolarConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Course_StudentEnrollment" Member="StudentEnrollments" ThisKey="Id" OtherKey="CourseId" Type="StudentEnrollment" />
      <Association Name="Course_TeachingAssignment" Member="TeachingAssignments" ThisKey="Id" OtherKey="CourseId" Type="TeachingAssignment" />
    </Type>
  </Table>
  <Table Name="dbo.EventProfessors" Member="EventProfessors">
    <Type Name="EventProfessor">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfessorId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Event_EventProfessor" Member="Event" ThisKey="EventId" OtherKey="EventId" Type="Event" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Professor_EventProfessor" Member="Professor" ThisKey="ProfessorId" OtherKey="ProfessorId" Type="Professor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Event_EventProfessor" Member="EventProfessors" ThisKey="EventId" OtherKey="EventId" Type="EventProfessor" />
      <Association Name="Event_EventStudent" Member="EventStudents" ThisKey="EventId" OtherKey="EventId" Type="EventStudent" />
    </Type>
  </Table>
  <Table Name="dbo.EventStudents" Member="EventStudents">
    <Type Name="EventStudent">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Event_EventStudent" Member="Event" ThisKey="EventId" OtherKey="EventId" Type="Event" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Student_EventStudent" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Grades" Member="Grades">
    <Type Name="Grade">
      <Column Name="GradeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnrollmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="StudentEnrollment_Grade" Member="StudentEnrollment" ThisKey="EnrollmentId" OtherKey="StudentEnrollmentId" Type="StudentEnrollment" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Professors" Member="Professors">
    <Type Name="Professor">
      <Column Name="ProfessorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Specialization" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Professor_EventProfessor" Member="EventProfessors" ThisKey="ProfessorId" OtherKey="ProfessorId" Type="EventProfessor" />
      <Association Name="Professor_TeachingAssignment" Member="TeachingAssignments" ThisKey="ProfessorId" OtherKey="ProfessorId" Type="TeachingAssignment" />
    </Type>
  </Table>
  <Table Name="dbo.StudentClassGroups" Member="StudentClassGroups">
    <Type Name="StudentClassGroup">
      <Column Name="StudentClassGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NightShift" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="StudentClassGroup_StudentEnrollment" Member="StudentEnrollments" ThisKey="StudentClassGroupId" OtherKey="GroupId" Type="StudentEnrollment" />
      <Association Name="StudentClassGroup_Student" Member="Students" ThisKey="StudentClassGroupId" OtherKey="GroupId" Type="Student" />
      <Association Name="StudentClassGroup_TeachingAssignment" Member="TeachingAssignments" ThisKey="StudentClassGroupId" OtherKey="GroupId" Type="TeachingAssignment" />
    </Type>
  </Table>
  <Table Name="dbo.StudentEnrollments" Member="StudentEnrollments">
    <Type Name="StudentEnrollment">
      <Column Name="StudentEnrollmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentEnrollment_Grade" Member="Grades" ThisKey="StudentEnrollmentId" OtherKey="EnrollmentId" Type="Grade" />
      <Association Name="Course_StudentEnrollment" Member="Course" ThisKey="CourseId" OtherKey="Id" Type="Course" IsForeignKey="true" />
      <Association Name="StudentClassGroup_StudentEnrollment" Member="StudentClassGroup" ThisKey="GroupId" OtherKey="StudentClassGroupId" Type="StudentClassGroup" IsForeignKey="true" />
      <Association Name="Student_StudentEnrollment" Member="Student" ThisKey="StudentId" OtherKey="StudentId" Type="Student" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Student_EventStudent" Member="EventStudents" ThisKey="StudentId" OtherKey="StudentId" Type="EventStudent" />
      <Association Name="Student_StudentEnrollment" Member="StudentEnrollments" ThisKey="StudentId" OtherKey="StudentId" Type="StudentEnrollment" />
      <Association Name="StudentClassGroup_Student" Member="StudentClassGroup" ThisKey="GroupId" OtherKey="StudentClassGroupId" Type="StudentClassGroup" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.TeachingAssignments" Member="TeachingAssignments">
    <Type Name="TeachingAssignment">
      <Column Name="TeachingAssignmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProfessorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_TeachingAssignment" Member="Course" ThisKey="CourseId" OtherKey="Id" Type="Course" IsForeignKey="true" />
      <Association Name="StudentClassGroup_TeachingAssignment" Member="StudentClassGroup" ThisKey="GroupId" OtherKey="StudentClassGroupId" Type="StudentClassGroup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Professor_TeachingAssignment" Member="Professor" ThisKey="ProfessorId" OtherKey="ProfessorId" Type="Professor" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Courses" Member="vw_Courses">
    <Type Name="vw_Course">
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_EnrollmentAverages" Member="vw_EnrollmentAverages">
    <Type Name="vw_EnrollmentAverage">
      <Column Name="EnrollmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="WeightedAverage" Type="System.Decimal" DbType="Decimal(4,2)" CanBeNull="true" />
      <Column Name="GradeCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_EventParticipants" Member="vw_EventParticipants">
    <Type Name="vw_EventParticipant">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantType" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Events" Member="vw_Events">
    <Type Name="vw_Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Grades" Member="vw_Grades">
    <Type Name="vw_Grade">
      <Column Name="GradeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnrollmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Professors" Member="vw_Professors">
    <Type Name="vw_Professor">
      <Column Name="ProfessorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Specialization" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_StudentClassGroups" Member="vw_StudentClassGroups">
    <Type Name="vw_StudentClassGroup">
      <Column Name="StudentClassGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NightShift" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_StudentEnrollments" Member="vw_StudentEnrollments">
    <Type Name="vw_StudentEnrollment">
      <Column Name="StudentEnrollmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GroupYear" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NightShift" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Students" Member="vw_Students">
    <Type Name="vw_Student">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GroupYear" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NightShift" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_TeachingAssignments" Member="vw_TeachingAssignments">
    <Type Name="vw_TeachingAssignment">
      <Column Name="TeachingAssignmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfessorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProfessorName" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="ProfessorSpecialization" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GroupYear" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NightShift" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="WeeklyHours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>