#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaGestaoEscolar")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCourse(Course instance);
    partial void UpdateCourse(Course instance);
    partial void DeleteCourse(Course instance);
    partial void InsertEventProfessor(EventProfessor instance);
    partial void UpdateEventProfessor(EventProfessor instance);
    partial void DeleteEventProfessor(EventProfessor instance);
    partial void InsertEvent(Event instance);
    partial void UpdateEvent(Event instance);
    partial void DeleteEvent(Event instance);
    partial void InsertEventStudent(EventStudent instance);
    partial void UpdateEventStudent(EventStudent instance);
    partial void DeleteEventStudent(EventStudent instance);
    partial void InsertGrade(Grade instance);
    partial void UpdateGrade(Grade instance);
    partial void DeleteGrade(Grade instance);
    partial void InsertProfessor(Professor instance);
    partial void UpdateProfessor(Professor instance);
    partial void DeleteProfessor(Professor instance);
    partial void InsertStudentClassGroup(StudentClassGroup instance);
    partial void UpdateStudentClassGroup(StudentClassGroup instance);
    partial void DeleteStudentClassGroup(StudentClassGroup instance);
    partial void InsertStudentEnrollment(StudentEnrollment instance);
    partial void UpdateStudentEnrollment(StudentEnrollment instance);
    partial void DeleteStudentEnrollment(StudentEnrollment instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertTeachingAssignment(TeachingAssignment instance);
    partial void UpdateTeachingAssignment(TeachingAssignment instance);
    partial void DeleteTeachingAssignment(TeachingAssignment instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SGE.Data.Properties.Settings.Default.SistemaGestaoEscolarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Course> Courses
		{
			get
			{
				return this.GetTable<Course>();
			}
		}
		
		public System.Data.Linq.Table<EventProfessor> EventProfessors
		{
			get
			{
				return this.GetTable<EventProfessor>();
			}
		}
		
		public System.Data.Linq.Table<Event> Events
		{
			get
			{
				return this.GetTable<Event>();
			}
		}
		
		public System.Data.Linq.Table<EventStudent> EventStudents
		{
			get
			{
				return this.GetTable<EventStudent>();
			}
		}
		
		public System.Data.Linq.Table<Grade> Grades
		{
			get
			{
				return this.GetTable<Grade>();
			}
		}
		
		public System.Data.Linq.Table<Professor> Professors
		{
			get
			{
				return this.GetTable<Professor>();
			}
		}
		
		public System.Data.Linq.Table<StudentClassGroup> StudentClassGroups
		{
			get
			{
				return this.GetTable<StudentClassGroup>();
			}
		}
		
		public System.Data.Linq.Table<StudentEnrollment> StudentEnrollments
		{
			get
			{
				return this.GetTable<StudentEnrollment>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<TeachingAssignment> TeachingAssignments
		{
			get
			{
				return this.GetTable<TeachingAssignment>();
			}
		}
		
		public System.Data.Linq.Table<vw_EnrollmentAverage> vw_EnrollmentAverages
		{
			get
			{
				return this.GetTable<vw_EnrollmentAverage>();
			}
		}
		
		public System.Data.Linq.Table<vw_EventParticipant> vw_EventParticipants
		{
			get
			{
				return this.GetTable<vw_EventParticipant>();
			}
		}
		
		public System.Data.Linq.Table<vw_Student> vw_Students
		{
			get
			{
				return this.GetTable<vw_Student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Courses")]
	public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _WeeklyHours;
		
		private bool _IsDeleted;
		
		private EntitySet<StudentEnrollment> _StudentEnrollments;
		
		private EntitySet<TeachingAssignment> _TeachingAssignments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnWeeklyHoursChanging(int value);
    partial void OnWeeklyHoursChanged();
    partial void OnIsDeletedChanging(bool value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public Course()
		{
			this._StudentEnrollments = new EntitySet<StudentEnrollment>(new Action<StudentEnrollment>(this.attach_StudentEnrollments), new Action<StudentEnrollment>(this.detach_StudentEnrollments));
			this._TeachingAssignments = new EntitySet<TeachingAssignment>(new Action<TeachingAssignment>(this.attach_TeachingAssignments), new Action<TeachingAssignment>(this.detach_TeachingAssignments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeeklyHours", DbType="Int NOT NULL")]
		public int WeeklyHours
		{
			get
			{
				return this._WeeklyHours;
			}
			set
			{
				if ((this._WeeklyHours != value))
				{
					this.OnWeeklyHoursChanging(value);
					this.SendPropertyChanging();
					this._WeeklyHours = value;
					this.SendPropertyChanged("WeeklyHours");
					this.OnWeeklyHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit NOT NULL")]
		public bool IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_StudentEnrollment", Storage="_StudentEnrollments", ThisKey="Id", OtherKey="CourseId")]
		public EntitySet<StudentEnrollment> StudentEnrollments
		{
			get
			{
				return this._StudentEnrollments;
			}
			set
			{
				this._StudentEnrollments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_TeachingAssignment", Storage="_TeachingAssignments", ThisKey="Id", OtherKey="CourseId")]
		public EntitySet<TeachingAssignment> TeachingAssignments
		{
			get
			{
				return this._TeachingAssignments;
			}
			set
			{
				this._TeachingAssignments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentEnrollments(StudentEnrollment entity)
		{
			this.SendPropertyChanging();
			entity.Course = this;
		}
		
		private void detach_StudentEnrollments(StudentEnrollment entity)
		{
			this.SendPropertyChanging();
			entity.Course = null;
		}
		
		private void attach_TeachingAssignments(TeachingAssignment entity)
		{
			this.SendPropertyChanging();
			entity.Course = this;
		}
		
		private void detach_TeachingAssignments(TeachingAssignment entity)
		{
			this.SendPropertyChanging();
			entity.Course = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventProfessors")]
	public partial class EventProfessor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EventId;
		
		private int _ProfessorId;
		
		private EntityRef<Event> _Event;
		
		private EntityRef<Professor> _Professor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnProfessorIdChanging(int value);
    partial void OnProfessorIdChanged();
    #endregion
		
		public EventProfessor()
		{
			this._Event = default(EntityRef<Event>);
			this._Professor = default(EntityRef<Professor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					if (this._Event.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProfessorId
		{
			get
			{
				return this._ProfessorId;
			}
			set
			{
				if ((this._ProfessorId != value))
				{
					if (this._Professor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfessorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessorId = value;
					this.SendPropertyChanged("ProfessorId");
					this.OnProfessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Event_EventProfessor", Storage="_Event", ThisKey="EventId", OtherKey="EventId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Event Event
		{
			get
			{
				return this._Event.Entity;
			}
			set
			{
				Event previousValue = this._Event.Entity;
				if (((previousValue != value) 
							|| (this._Event.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Event.Entity = null;
						previousValue.EventProfessors.Remove(this);
					}
					this._Event.Entity = value;
					if ((value != null))
					{
						value.EventProfessors.Add(this);
						this._EventId = value.EventId;
					}
					else
					{
						this._EventId = default(int);
					}
					this.SendPropertyChanged("Event");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professor_EventProfessor", Storage="_Professor", ThisKey="ProfessorId", OtherKey="ProfessorId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Professor Professor
		{
			get
			{
				return this._Professor.Entity;
			}
			set
			{
				Professor previousValue = this._Professor.Entity;
				if (((previousValue != value) 
							|| (this._Professor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Professor.Entity = null;
						previousValue.EventProfessors.Remove(this);
					}
					this._Professor.Entity = value;
					if ((value != null))
					{
						value.EventProfessors.Add(this);
						this._ProfessorId = value.ProfessorId;
					}
					else
					{
						this._ProfessorId = default(int);
					}
					this.SendPropertyChanged("Professor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Events")]
	public partial class Event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EventId;
		
		private string _Name;
		
		private string _Type;
		
		private System.DateTime _Date;
		
		private string _Location;
		
		private string _Description;
		
		private EntitySet<EventProfessor> _EventProfessors;
		
		private EntitySet<EventStudent> _EventStudents;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public Event()
		{
			this._EventProfessors = new EntitySet<EventProfessor>(new Action<EventProfessor>(this.attach_EventProfessors), new Action<EventProfessor>(this.detach_EventProfessors));
			this._EventStudents = new EntitySet<EventStudent>(new Action<EventStudent>(this.attach_EventStudents), new Action<EventStudent>(this.detach_EventStudents));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Event_EventProfessor", Storage="_EventProfessors", ThisKey="EventId", OtherKey="EventId")]
		public EntitySet<EventProfessor> EventProfessors
		{
			get
			{
				return this._EventProfessors;
			}
			set
			{
				this._EventProfessors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Event_EventStudent", Storage="_EventStudents", ThisKey="EventId", OtherKey="EventId")]
		public EntitySet<EventStudent> EventStudents
		{
			get
			{
				return this._EventStudents;
			}
			set
			{
				this._EventStudents.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EventProfessors(EventProfessor entity)
		{
			this.SendPropertyChanging();
			entity.Event = this;
		}
		
		private void detach_EventProfessors(EventProfessor entity)
		{
			this.SendPropertyChanging();
			entity.Event = null;
		}
		
		private void attach_EventStudents(EventStudent entity)
		{
			this.SendPropertyChanging();
			entity.Event = this;
		}
		
		private void detach_EventStudents(EventStudent entity)
		{
			this.SendPropertyChanging();
			entity.Event = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EventStudents")]
	public partial class EventStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EventId;
		
		private int _StudentId;
		
		private EntityRef<Event> _Event;
		
		private EntityRef<Student> _Student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnStudentIdChanging(int value);
    partial void OnStudentIdChanged();
    #endregion
		
		public EventStudent()
		{
			this._Event = default(EntityRef<Event>);
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					if (this._Event.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Event_EventStudent", Storage="_Event", ThisKey="EventId", OtherKey="EventId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Event Event
		{
			get
			{
				return this._Event.Entity;
			}
			set
			{
				Event previousValue = this._Event.Entity;
				if (((previousValue != value) 
							|| (this._Event.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Event.Entity = null;
						previousValue.EventStudents.Remove(this);
					}
					this._Event.Entity = value;
					if ((value != null))
					{
						value.EventStudents.Add(this);
						this._EventId = value.EventId;
					}
					else
					{
						this._EventId = default(int);
					}
					this.SendPropertyChanged("Event");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_EventStudent", Storage="_Student", ThisKey="StudentId", OtherKey="StudentId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.EventStudents.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.EventStudents.Add(this);
						this._StudentId = value.StudentId;
					}
					else
					{
						this._StudentId = default(int);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grades")]
	public partial class Grade : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GradeId;
		
		private int _EnrollmentId;
		
		private decimal _Value;
		
		private decimal _Weight;
		
		private string _Type;
		
		private System.DateTime _Date;
		
		private EntityRef<StudentEnrollment> _StudentEnrollment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGradeIdChanging(int value);
    partial void OnGradeIdChanged();
    partial void OnEnrollmentIdChanging(int value);
    partial void OnEnrollmentIdChanged();
    partial void OnValueChanging(decimal value);
    partial void OnValueChanged();
    partial void OnWeightChanging(decimal value);
    partial void OnWeightChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    #endregion
		
		public Grade()
		{
			this._StudentEnrollment = default(EntityRef<StudentEnrollment>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GradeId
		{
			get
			{
				return this._GradeId;
			}
			set
			{
				if ((this._GradeId != value))
				{
					this.OnGradeIdChanging(value);
					this.SendPropertyChanging();
					this._GradeId = value;
					this.SendPropertyChanged("GradeId");
					this.OnGradeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollmentId", DbType="Int NOT NULL")]
		public int EnrollmentId
		{
			get
			{
				return this._EnrollmentId;
			}
			set
			{
				if ((this._EnrollmentId != value))
				{
					if (this._StudentEnrollment.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEnrollmentIdChanging(value);
					this.SendPropertyChanging();
					this._EnrollmentId = value;
					this.SendPropertyChanged("EnrollmentId");
					this.OnEnrollmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Decimal(4,2) NOT NULL")]
		public decimal Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(5,2) NOT NULL")]
		public decimal Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentEnrollment_Grade", Storage="_StudentEnrollment", ThisKey="EnrollmentId", OtherKey="StudentEnrollmentId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public StudentEnrollment StudentEnrollment
		{
			get
			{
				return this._StudentEnrollment.Entity;
			}
			set
			{
				StudentEnrollment previousValue = this._StudentEnrollment.Entity;
				if (((previousValue != value) 
							|| (this._StudentEnrollment.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentEnrollment.Entity = null;
						previousValue.Grades.Remove(this);
					}
					this._StudentEnrollment.Entity = value;
					if ((value != null))
					{
						value.Grades.Add(this);
						this._EnrollmentId = value.StudentEnrollmentId;
					}
					else
					{
						this._EnrollmentId = default(int);
					}
					this.SendPropertyChanged("StudentEnrollment");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Professors")]
	public partial class Professor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProfessorId;
		
		private string _Name;
		
		private string _Surname;
		
		private string _Contact;
		
		private string _Email;
		
		private string _Specialization;
		
		private EntitySet<EventProfessor> _EventProfessors;
		
		private EntitySet<TeachingAssignment> _TeachingAssignments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProfessorIdChanging(int value);
    partial void OnProfessorIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSpecializationChanging(string value);
    partial void OnSpecializationChanged();
    #endregion
		
		public Professor()
		{
			this._EventProfessors = new EntitySet<EventProfessor>(new Action<EventProfessor>(this.attach_EventProfessors), new Action<EventProfessor>(this.detach_EventProfessors));
			this._TeachingAssignments = new EntitySet<TeachingAssignment>(new Action<TeachingAssignment>(this.attach_TeachingAssignments), new Action<TeachingAssignment>(this.detach_TeachingAssignments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProfessorId
		{
			get
			{
				return this._ProfessorId;
			}
			set
			{
				if ((this._ProfessorId != value))
				{
					this.OnProfessorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessorId = value;
					this.SendPropertyChanged("ProfessorId");
					this.OnProfessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specialization", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Specialization
		{
			get
			{
				return this._Specialization;
			}
			set
			{
				if ((this._Specialization != value))
				{
					this.OnSpecializationChanging(value);
					this.SendPropertyChanging();
					this._Specialization = value;
					this.SendPropertyChanged("Specialization");
					this.OnSpecializationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professor_EventProfessor", Storage="_EventProfessors", ThisKey="ProfessorId", OtherKey="ProfessorId")]
		public EntitySet<EventProfessor> EventProfessors
		{
			get
			{
				return this._EventProfessors;
			}
			set
			{
				this._EventProfessors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professor_TeachingAssignment", Storage="_TeachingAssignments", ThisKey="ProfessorId", OtherKey="ProfessorId")]
		public EntitySet<TeachingAssignment> TeachingAssignments
		{
			get
			{
				return this._TeachingAssignments;
			}
			set
			{
				this._TeachingAssignments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EventProfessors(EventProfessor entity)
		{
			this.SendPropertyChanging();
			entity.Professor = this;
		}
		
		private void detach_EventProfessors(EventProfessor entity)
		{
			this.SendPropertyChanging();
			entity.Professor = null;
		}
		
		private void attach_TeachingAssignments(TeachingAssignment entity)
		{
			this.SendPropertyChanging();
			entity.Professor = this;
		}
		
		private void detach_TeachingAssignments(TeachingAssignment entity)
		{
			this.SendPropertyChanging();
			entity.Professor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentClassGroups")]
	public partial class StudentClassGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentClassGroupId;
		
		private string _Name;
		
		private string _Year;
		
		private bool _NightShift;
		
		private EntitySet<StudentEnrollment> _StudentEnrollments;
		
		private EntitySet<Student> _Students;
		
		private EntitySet<TeachingAssignment> _TeachingAssignments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentClassGroupIdChanging(int value);
    partial void OnStudentClassGroupIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnNightShiftChanging(bool value);
    partial void OnNightShiftChanged();
    #endregion
		
		public StudentClassGroup()
		{
			this._StudentEnrollments = new EntitySet<StudentEnrollment>(new Action<StudentEnrollment>(this.attach_StudentEnrollments), new Action<StudentEnrollment>(this.detach_StudentEnrollments));
			this._Students = new EntitySet<Student>(new Action<Student>(this.attach_Students), new Action<Student>(this.detach_Students));
			this._TeachingAssignments = new EntitySet<TeachingAssignment>(new Action<TeachingAssignment>(this.attach_TeachingAssignments), new Action<TeachingAssignment>(this.detach_TeachingAssignments));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentClassGroupId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudentClassGroupId
		{
			get
			{
				return this._StudentClassGroupId;
			}
			set
			{
				if ((this._StudentClassGroupId != value))
				{
					this.OnStudentClassGroupIdChanging(value);
					this.SendPropertyChanging();
					this._StudentClassGroupId = value;
					this.SendPropertyChanged("StudentClassGroupId");
					this.OnStudentClassGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NightShift", DbType="Bit NOT NULL")]
		public bool NightShift
		{
			get
			{
				return this._NightShift;
			}
			set
			{
				if ((this._NightShift != value))
				{
					this.OnNightShiftChanging(value);
					this.SendPropertyChanging();
					this._NightShift = value;
					this.SendPropertyChanged("NightShift");
					this.OnNightShiftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentClassGroup_StudentEnrollment", Storage="_StudentEnrollments", ThisKey="StudentClassGroupId", OtherKey="GroupId")]
		public EntitySet<StudentEnrollment> StudentEnrollments
		{
			get
			{
				return this._StudentEnrollments;
			}
			set
			{
				this._StudentEnrollments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentClassGroup_Student", Storage="_Students", ThisKey="StudentClassGroupId", OtherKey="GroupId")]
		public EntitySet<Student> Students
		{
			get
			{
				return this._Students;
			}
			set
			{
				this._Students.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentClassGroup_TeachingAssignment", Storage="_TeachingAssignments", ThisKey="StudentClassGroupId", OtherKey="GroupId")]
		public EntitySet<TeachingAssignment> TeachingAssignments
		{
			get
			{
				return this._TeachingAssignments;
			}
			set
			{
				this._TeachingAssignments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_StudentEnrollments(StudentEnrollment entity)
		{
			this.SendPropertyChanging();
			entity.StudentClassGroup = this;
		}
		
		private void detach_StudentEnrollments(StudentEnrollment entity)
		{
			this.SendPropertyChanging();
			entity.StudentClassGroup = null;
		}
		
		private void attach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.StudentClassGroup = this;
		}
		
		private void detach_Students(Student entity)
		{
			this.SendPropertyChanging();
			entity.StudentClassGroup = null;
		}
		
		private void attach_TeachingAssignments(TeachingAssignment entity)
		{
			this.SendPropertyChanging();
			entity.StudentClassGroup = this;
		}
		
		private void detach_TeachingAssignments(TeachingAssignment entity)
		{
			this.SendPropertyChanging();
			entity.StudentClassGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentEnrollments")]
	public partial class StudentEnrollment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentEnrollmentId;
		
		private int _StudentId;
		
		private int _CourseId;
		
		private int _GroupId;
		
		private EntitySet<Grade> _Grades;
		
		private EntityRef<Course> _Course;
		
		private EntityRef<StudentClassGroup> _StudentClassGroup;
		
		private EntityRef<Student> _Student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentEnrollmentIdChanging(int value);
    partial void OnStudentEnrollmentIdChanged();
    partial void OnStudentIdChanging(int value);
    partial void OnStudentIdChanged();
    partial void OnCourseIdChanging(int value);
    partial void OnCourseIdChanged();
    partial void OnGroupIdChanging(int value);
    partial void OnGroupIdChanged();
    #endregion
		
		public StudentEnrollment()
		{
			this._Grades = new EntitySet<Grade>(new Action<Grade>(this.attach_Grades), new Action<Grade>(this.detach_Grades));
			this._Course = default(EntityRef<Course>);
			this._StudentClassGroup = default(EntityRef<StudentClassGroup>);
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentEnrollmentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudentEnrollmentId
		{
			get
			{
				return this._StudentEnrollmentId;
			}
			set
			{
				if ((this._StudentEnrollmentId != value))
				{
					this.OnStudentEnrollmentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentEnrollmentId = value;
					this.SendPropertyChanged("StudentEnrollmentId");
					this.OnStudentEnrollmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="Int NOT NULL")]
		public int StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseId", DbType="Int NOT NULL")]
		public int CourseId
		{
			get
			{
				return this._CourseId;
			}
			set
			{
				if ((this._CourseId != value))
				{
					if (this._Course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCourseIdChanging(value);
					this.SendPropertyChanging();
					this._CourseId = value;
					this.SendPropertyChanged("CourseId");
					this.OnCourseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._StudentClassGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentEnrollment_Grade", Storage="_Grades", ThisKey="StudentEnrollmentId", OtherKey="EnrollmentId")]
		public EntitySet<Grade> Grades
		{
			get
			{
				return this._Grades;
			}
			set
			{
				this._Grades.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_StudentEnrollment", Storage="_Course", ThisKey="CourseId", OtherKey="Id", IsForeignKey=true)]
		public Course Course
		{
			get
			{
				return this._Course.Entity;
			}
			set
			{
				Course previousValue = this._Course.Entity;
				if (((previousValue != value) 
							|| (this._Course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Course.Entity = null;
						previousValue.StudentEnrollments.Remove(this);
					}
					this._Course.Entity = value;
					if ((value != null))
					{
						value.StudentEnrollments.Add(this);
						this._CourseId = value.Id;
					}
					else
					{
						this._CourseId = default(int);
					}
					this.SendPropertyChanged("Course");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentClassGroup_StudentEnrollment", Storage="_StudentClassGroup", ThisKey="GroupId", OtherKey="StudentClassGroupId", IsForeignKey=true)]
		public StudentClassGroup StudentClassGroup
		{
			get
			{
				return this._StudentClassGroup.Entity;
			}
			set
			{
				StudentClassGroup previousValue = this._StudentClassGroup.Entity;
				if (((previousValue != value) 
							|| (this._StudentClassGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentClassGroup.Entity = null;
						previousValue.StudentEnrollments.Remove(this);
					}
					this._StudentClassGroup.Entity = value;
					if ((value != null))
					{
						value.StudentEnrollments.Add(this);
						this._GroupId = value.StudentClassGroupId;
					}
					else
					{
						this._GroupId = default(int);
					}
					this.SendPropertyChanged("StudentClassGroup");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StudentEnrollment", Storage="_Student", ThisKey="StudentId", OtherKey="StudentId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.StudentEnrollments.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.StudentEnrollments.Add(this);
						this._StudentId = value.StudentId;
					}
					else
					{
						this._StudentId = default(int);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Grades(Grade entity)
		{
			this.SendPropertyChanging();
			entity.StudentEnrollment = this;
		}
		
		private void detach_Grades(Grade entity)
		{
			this.SendPropertyChanging();
			entity.StudentEnrollment = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Students")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentId;
		
		private string _Name;
		
		private string _Surname;
		
		private System.DateTime _DOB;
		
		private string _Contact;
		
		private string _Address;
		
		private string _Email;
		
		private System.Nullable<int> _GroupId;
		
		private EntitySet<EventStudent> _EventStudents;
		
		private EntitySet<StudentEnrollment> _StudentEnrollments;
		
		private EntityRef<StudentClassGroup> _StudentClassGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIdChanging(int value);
    partial void OnStudentIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnGroupIdChanging(System.Nullable<int> value);
    partial void OnGroupIdChanged();
    #endregion
		
		public Student()
		{
			this._EventStudents = new EntitySet<EventStudent>(new Action<EventStudent>(this.attach_EventStudents), new Action<EventStudent>(this.detach_EventStudents));
			this._StudentEnrollments = new EntitySet<StudentEnrollment>(new Action<StudentEnrollment>(this.attach_StudentEnrollments), new Action<StudentEnrollment>(this.detach_StudentEnrollments));
			this._StudentClassGroup = default(EntityRef<StudentClassGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					this.OnStudentIdChanging(value);
					this.SendPropertyChanging();
					this._StudentId = value;
					this.SendPropertyChanged("StudentId");
					this.OnStudentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
		public System.Nullable<int> GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._StudentClassGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_EventStudent", Storage="_EventStudents", ThisKey="StudentId", OtherKey="StudentId")]
		public EntitySet<EventStudent> EventStudents
		{
			get
			{
				return this._EventStudents;
			}
			set
			{
				this._EventStudents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StudentEnrollment", Storage="_StudentEnrollments", ThisKey="StudentId", OtherKey="StudentId")]
		public EntitySet<StudentEnrollment> StudentEnrollments
		{
			get
			{
				return this._StudentEnrollments;
			}
			set
			{
				this._StudentEnrollments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentClassGroup_Student", Storage="_StudentClassGroup", ThisKey="GroupId", OtherKey="StudentClassGroupId", IsForeignKey=true, DeleteRule="SET NULL")]
		public StudentClassGroup StudentClassGroup
		{
			get
			{
				return this._StudentClassGroup.Entity;
			}
			set
			{
				StudentClassGroup previousValue = this._StudentClassGroup.Entity;
				if (((previousValue != value) 
							|| (this._StudentClassGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentClassGroup.Entity = null;
						previousValue.Students.Remove(this);
					}
					this._StudentClassGroup.Entity = value;
					if ((value != null))
					{
						value.Students.Add(this);
						this._GroupId = value.StudentClassGroupId;
					}
					else
					{
						this._GroupId = default(Nullable<int>);
					}
					this.SendPropertyChanged("StudentClassGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EventStudents(EventStudent entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_EventStudents(EventStudent entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
		
		private void attach_StudentEnrollments(StudentEnrollment entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_StudentEnrollments(StudentEnrollment entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TeachingAssignments")]
	public partial class TeachingAssignment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeachingAssignmentId;
		
		private int _ProfessorId;
		
		private int _GroupId;
		
		private int _CourseId;
		
		private EntityRef<Course> _Course;
		
		private EntityRef<StudentClassGroup> _StudentClassGroup;
		
		private EntityRef<Professor> _Professor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeachingAssignmentIdChanging(int value);
    partial void OnTeachingAssignmentIdChanged();
    partial void OnProfessorIdChanging(int value);
    partial void OnProfessorIdChanged();
    partial void OnGroupIdChanging(int value);
    partial void OnGroupIdChanged();
    partial void OnCourseIdChanging(int value);
    partial void OnCourseIdChanged();
    #endregion
		
		public TeachingAssignment()
		{
			this._Course = default(EntityRef<Course>);
			this._StudentClassGroup = default(EntityRef<StudentClassGroup>);
			this._Professor = default(EntityRef<Professor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeachingAssignmentId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TeachingAssignmentId
		{
			get
			{
				return this._TeachingAssignmentId;
			}
			set
			{
				if ((this._TeachingAssignmentId != value))
				{
					this.OnTeachingAssignmentIdChanging(value);
					this.SendPropertyChanging();
					this._TeachingAssignmentId = value;
					this.SendPropertyChanged("TeachingAssignmentId");
					this.OnTeachingAssignmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessorId", DbType="Int NOT NULL")]
		public int ProfessorId
		{
			get
			{
				return this._ProfessorId;
			}
			set
			{
				if ((this._ProfessorId != value))
				{
					if (this._Professor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfessorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessorId = value;
					this.SendPropertyChanged("ProfessorId");
					this.OnProfessorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					if (this._StudentClassGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseId", DbType="Int NOT NULL")]
		public int CourseId
		{
			get
			{
				return this._CourseId;
			}
			set
			{
				if ((this._CourseId != value))
				{
					if (this._Course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCourseIdChanging(value);
					this.SendPropertyChanging();
					this._CourseId = value;
					this.SendPropertyChanged("CourseId");
					this.OnCourseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Course_TeachingAssignment", Storage="_Course", ThisKey="CourseId", OtherKey="Id", IsForeignKey=true)]
		public Course Course
		{
			get
			{
				return this._Course.Entity;
			}
			set
			{
				Course previousValue = this._Course.Entity;
				if (((previousValue != value) 
							|| (this._Course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Course.Entity = null;
						previousValue.TeachingAssignments.Remove(this);
					}
					this._Course.Entity = value;
					if ((value != null))
					{
						value.TeachingAssignments.Add(this);
						this._CourseId = value.Id;
					}
					else
					{
						this._CourseId = default(int);
					}
					this.SendPropertyChanged("Course");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StudentClassGroup_TeachingAssignment", Storage="_StudentClassGroup", ThisKey="GroupId", OtherKey="StudentClassGroupId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public StudentClassGroup StudentClassGroup
		{
			get
			{
				return this._StudentClassGroup.Entity;
			}
			set
			{
				StudentClassGroup previousValue = this._StudentClassGroup.Entity;
				if (((previousValue != value) 
							|| (this._StudentClassGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentClassGroup.Entity = null;
						previousValue.TeachingAssignments.Remove(this);
					}
					this._StudentClassGroup.Entity = value;
					if ((value != null))
					{
						value.TeachingAssignments.Add(this);
						this._GroupId = value.StudentClassGroupId;
					}
					else
					{
						this._GroupId = default(int);
					}
					this.SendPropertyChanged("StudentClassGroup");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Professor_TeachingAssignment", Storage="_Professor", ThisKey="ProfessorId", OtherKey="ProfessorId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Professor Professor
		{
			get
			{
				return this._Professor.Entity;
			}
			set
			{
				Professor previousValue = this._Professor.Entity;
				if (((previousValue != value) 
							|| (this._Professor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Professor.Entity = null;
						previousValue.TeachingAssignments.Remove(this);
					}
					this._Professor.Entity = value;
					if ((value != null))
					{
						value.TeachingAssignments.Add(this);
						this._ProfessorId = value.ProfessorId;
					}
					else
					{
						this._ProfessorId = default(int);
					}
					this.SendPropertyChanged("Professor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_EnrollmentAverages")]
	public partial class vw_EnrollmentAverage
	{
		
		private int _EnrollmentId;
		
		private int _StudentId;
		
		private int _CourseId;
		
		private int _GroupId;
		
		private string _StudentName;
		
		private string _CourseName;
		
		private string _GroupName;
		
		private System.Nullable<decimal> _WeightedAverage;
		
		private System.Nullable<int> _GradeCount;
		
		public vw_EnrollmentAverage()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollmentId", DbType="Int NOT NULL")]
		public int EnrollmentId
		{
			get
			{
				return this._EnrollmentId;
			}
			set
			{
				if ((this._EnrollmentId != value))
				{
					this._EnrollmentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="Int NOT NULL")]
		public int StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					this._StudentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseId", DbType="Int NOT NULL")]
		public int CourseId
		{
			get
			{
				return this._CourseId;
			}
			set
			{
				if ((this._CourseId != value))
				{
					this._CourseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentName", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string StudentName
		{
			get
			{
				return this._StudentName;
			}
			set
			{
				if ((this._StudentName != value))
				{
					this._StudentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string CourseName
		{
			get
			{
				return this._CourseName;
			}
			set
			{
				if ((this._CourseName != value))
				{
					this._CourseName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeightedAverage", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> WeightedAverage
		{
			get
			{
				return this._WeightedAverage;
			}
			set
			{
				if ((this._WeightedAverage != value))
				{
					this._WeightedAverage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeCount", DbType="Int")]
		public System.Nullable<int> GradeCount
		{
			get
			{
				return this._GradeCount;
			}
			set
			{
				if ((this._GradeCount != value))
				{
					this._GradeCount = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_EventParticipants")]
	public partial class vw_EventParticipant
	{
		
		private int _EventId;
		
		private string _EventName;
		
		private System.DateTime _EventDate;
		
		private int _ParticipantId;
		
		private string _ParticipantType;
		
		private string _ParticipantName;
		
		public vw_EventParticipant()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL")]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this._EventId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string EventName
		{
			get
			{
				return this._EventName;
			}
			set
			{
				if ((this._EventName != value))
				{
					this._EventName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventDate", DbType="DateTime NOT NULL")]
		public System.DateTime EventDate
		{
			get
			{
				return this._EventDate;
			}
			set
			{
				if ((this._EventDate != value))
				{
					this._EventDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParticipantId", DbType="Int NOT NULL")]
		public int ParticipantId
		{
			get
			{
				return this._ParticipantId;
			}
			set
			{
				if ((this._ParticipantId != value))
				{
					this._ParticipantId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParticipantType", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string ParticipantType
		{
			get
			{
				return this._ParticipantType;
			}
			set
			{
				if ((this._ParticipantType != value))
				{
					this._ParticipantType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParticipantName", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string ParticipantName
		{
			get
			{
				return this._ParticipantName;
			}
			set
			{
				if ((this._ParticipantName != value))
				{
					this._ParticipantName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Students")]
	public partial class vw_Student
	{
		
		private int _StudentId;
		
		private string _Name;
		
		private string _Surname;
		
		private string _FullName;
		
		private System.DateTime _DOB;
		
		private string _Contact;
		
		private string _Address;
		
		private string _Email;
		
		private System.Nullable<int> _GroupId;
		
		private string _GroupName;
		
		private string _GroupYear;
		
		private System.Nullable<bool> _NightShift;
		
		public vw_Student()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentId", DbType="Int NOT NULL")]
		public int StudentId
		{
			get
			{
				return this._StudentId;
			}
			set
			{
				if ((this._StudentId != value))
				{
					this._StudentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(201) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this._DOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
		public System.Nullable<int> GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(100)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupYear", DbType="NVarChar(20)")]
		public string GroupYear
		{
			get
			{
				return this._GroupYear;
			}
			set
			{
				if ((this._GroupYear != value))
				{
					this._GroupYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NightShift", DbType="Bit")]
		public System.Nullable<bool> NightShift
		{
			get
			{
				return this._NightShift;
			}
			set
			{
				if ((this._NightShift != value))
				{
					this._NightShift = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
